version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=development
      - DEBUG=True
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080
    volumes:
      - .:/app
    # Health check for local testing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s